### ISSUE TITLE
some problem~~~plz~~~

### ISSUE THREAD

**Issue by pangzhiyu** [billysx/network_lab_pensieve#1]
Dear author，
Thanks for your code！
Now I am running your code，and I want to know how many “Process” and “episode” this code will run。Could you tell  me？plz~~
Because I just use my personal computer to run this code。

**Comment by pangzhiyu** [comment]
And now。
The train has some problem。

BrokenPipeError: [WinError 109] 管道已结束。



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\torch\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\torch\lib\site-packages\tensorboardX\event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "D:\Anaconda\envs\torch\lib\multiprocessing\queues.py", line 117, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\torch\lib\multiprocessing\connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\torch\lib\multiprocessing\connection.py", line 326, in _recv_bytes
    raise EOFError
EOFError
